<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MohammadRifatAmins-MacBook-Air.local" ignored="1" name="Default test(failed)(failed)" tests="2" failures="1" timestamp="2020-12-14T16:58:12 EST" time="0.103" errors="0">
  <testcase name="test2" time="0.022" classname="com.testNG.HomeTest">
    <failure type="java.lang.AssertionError" message="Don&amp;apos;t worry expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Don't worry expected [true] but found [false]
at com.testNG.HomeTest.test2(HomeTest.java:57)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.testNG.HomeTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="com.testNG.HomeTest">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed)(failed) -->
